"""Candidate scaffold generated by the Angel bounty pipeline."""
from __future__ import annotations

REQUIREMENT = "Add support for `/title`"

def candidate_summary() -> dict:
    """Self-consistent summary of this candidate change."""
    return {"requirement": REQUIREMENT}
